---
- name: GitHub Role with Debug and Conditions
  hosts: all 
  gather_facts: true
  roles:
    - role: "Test_Ansible"
 

 
  # handlers:
  #   - name: Restart Service
  #     service:
  #       name: your-service
  #       state: restarted
 
 
 
