- name: GitHub Role with Debug and Conditions
  hosts: localhost
  gather_facts: false
 
  tasks:
    - name: Clone GitHub Repository
      git:
        repo: https://github.com/AGpawar/ansible_TestRepo
      register: git_clone_output
 
    - name: Debug Git Clone Output
      debug:
        var: git_clone_output.stdout_lines
      register: debug_output
 
    - name: Set Fact based on Debug Output
      set_fact:
        parameter_value: "{{ debug_output.stdout_lines[0] }}"  # Adjust this based on your debug output
 
    
 
 
 
