       - name: copy file
        hosts: all
        become: true
        gather_facts: false
          ansible.builtin.copy:
           src: C:\Users\apaw\asx.txt
           dest: C:\Users\apaw\Searches
             roles:
              - role: "Test_Ansible"