 --- 
 - hosts: all
   tasks:
  - name: Creates directory
    file:
     path: "C:\Users\apaw\{{test1}}"
     state: directory


- hosts: all
  tasks:
  - name: Creating an empty file
    file:
      path: "C:\Users\apaw\test_file.txt"
      state: touch
