- name: directory   
  file:
    path: "{{ dest_folder }}"
    state: directory
    mode: '0755'
- name: Copy each file over that matches the given pattern
  ansible.builtin.copy:
      src:  ./files/
      dest: /etc/Searches
      owner: "apaw"
      mode: 0600
- name: hostname
      command: hostname
      register: command_output
- name: cat /etc/redhat-release
      command: cat redhat-release chdir=/etc      
- name: Create your local file 
  ansible.builtin.file:
      path: "{{ dest_folder }}"
      owner: "apaw"
      mode: 0644
- name: Print output to file
  ansible.builtin.copy:
      content: "{{command_output.stdout}}"
      dest: /etc/Searches
      