- name: directory   
  file:
    path: "{{ dest_folder }}"
    state: directory
    mode: '0755'
- name: Copy each file over that matches the given pattern
  ansible.builtin.copy:
      src:  ./files/
      dest: /etc/Searches
      owner: "apaw"
      mode: '0600'
- name: Create your local file 
  ansible.builtin.file:
      path: "{{ dest_folder }}"
      owner: "apaw"
      mode: '0644'
- name: List file and folder in home directory 
  shell: 'ls -l'
  register: command_output
#- name: Print output to file
#  ansible.builtin.copy:
#      content: "{{command_output.stdout}}"
#      dest: /etc/Searches
- name: Print to console
  ansible.builtin.debug:
        msg: command_output.stdout

#- name: Display content of resolv.conf
#  hosts: localhost      
#- name: Display contents
#      command: cat resolv.conf chdir=/etc
#      register: command_output
#- name: Print to console
#      debug:
#        msg: "{{command_output.stdout}}"

      