- name: directory   
  file:
    path: "{{ dest_folder }}"
    state: directory
    mode: '0755'
- name: Copy each file over that matches the given pattern
  ansible.builtin.copy:
      src:  ./files/
      dest: /etc/Searches
      owner: "apaw"
      mode: '0600'
  register: file_copied

- name: Show All print message using block
  block:  
- name: show message if file was copied
  ansible.builtin.debug: 
       msg: "The user file already copy"
  when: /etc/Searches == file_copied is succeeded
  
- name: File not copied
  ansible.builtin.debug: 
       msg: "File not copied"
  when: /etc/Searches == file_copied is unsucceeded
  become: true
  become_user: root
  ignore_errors: true
  
  

#- name: Show All print message using block
#  block:
#    - name: File copied
#      ansible.builtin.debug: 
#         msg: "The user file copy"
#  when: file_copied is succeeded
    
#  become: true
#  become_user: root
#  ignore_errors: true

- name: Run the command if "file_copied" is true
  ansible.builtin.shell: echo "file_copied is changed!"
  when: file_copied is changed
- name: Run the command if "file_copied" is false
  ansible.builtin.shell: echo "File_copied is not changed!"
  when: file_copied is not changed


- name: Create your local file 
  ansible.builtin.file:
      path: /etc/Searches/abc.txt
      state: "touch"
      owner: "apaw"
      mode: '0644'
- name: List file and folder in home directory 
  shell: 'ls -l'
  register: command_output
#- name: Print output to file
#  ansible.builtin.copy:
#      content: command_output.stdout
#      dest: /etc/Searches
- name: Print to file
  ansible.builtin.debug:
      msg: "Hello world!"
  register: ansible_first_output 
- name: Get the output
  ansible.builtin.copy:
      content: "{{ansible_first_output}}"
      dest: /etc/Searches/abc.txt


#- name: file copy
#  ansible.builtin.debug:
#      msg: "copying file done"
#  register: Copying_File_done            
- name: Register a variable
  ansible.builtin.shell: cat /etc/Searches/abc.txt
  register: Searches_contents
  
#- name: condition check
#  ansible.builtin.shell: 
#     msg: "Searches_contains_the_word_Hello"
#  when: Searches_contents.stdout.find('Hello') != -1

#- name: Creates Folder
#    win_file:
#        path: /etc/Searches/
#  register: Folder_create
- name: create folder
  ansible.builtin.debug:
      msg: "Folder create"
  register: Folder_create
  


#- name: Get message
#  community.windows.win_file_version:
#    path: /etc/Searches/abc.txt
#  register: print_a_msg_about_when_the_folder_created
#    debug:
 #       msg: '{{ print a msg about when the folder created }}'


#- name: Append to /etc/Searches
#  command: cat /home/EUR/apaw/home/test.txt >> /etc/Searches/abc.txt


#- name: Display content of resolv.conf2
#  hosts: localhost      
#- name: Display contents
#      command: cat resolv.conf chdir=/etc
#      register: command_output
#- name: Print to console
#      debug:
#        msg: "{{command_outp ut.stdout}}"

    