---
-name : main
- hosts: all
  tasks:
  - name: Creating a file with content
    copy:
      dest: "C:\Users\apaw\Test_code\ansible_TestRepo\{{test1}}"
      content: |
        line 01
        line 02

