- name: directory   
  file:
    path: "{{ dest_folder }}"
    state: directory
    mode: '0755'
- name: Copy each file over that matches the given pattern
  ansible.builtin.copy:
      src:  ./files/
      dest: /etc/Searches
      owner: "apaw"
      mode: '0600'
- name: Create your local file 
  ansible.builtin.file:
      path: /etc/Searches/abc.txt
      state: "touch"
      owner: "apaw"
      mode: '0644'
- name: List file and folder in home directory 
  shell: 'ls -l'
  register: command_output
#- name: Print output to file
#  ansible.builtin.copy:
#      content: command_output.stdout
#      dest: /etc/Searches
- name: Print to file
  ansible.builtin.debug:
      msg: "Hello world!"
  register: ansible_first_output
- name: Get the output
  ansible.builtin.copy:
      content: "{{ansible_first_output}}"
      dest: /etc/Searches/abc.txt
- name: Register a variable
        ansible.builtin.shell: cat /etc/Searches
        register: Searches_contents
- name: Use the variable in conditional statement
        ansible.builtin.shell: echo "Searches contains the word my"
        when: Searches_contents.stdout.find('my') != -1

#- name: Append to /etc/Searches
#  command: cat /home/EUR/apaw/home/test.txt >> /etc/Searches/abc.txt


#- name: Display content of resolv.conf2
#  hosts: localhost      
#- name: Display contents
#      command: cat resolv.conf chdir=/etc
#      register: command_output
#- name: Print to console
#      debug:
#        msg: "{{command_outp ut.stdout}}"

    