- name: directory   
  file:
    path: "{{ dest_folder }}"
    state: directory
    mode: '0755'
- name: Copy each file over that matches the given pattern
  ansible.builtin.copy:
      src:  ./files/
      dest: /etc/Searches
      owner: "apaw"
      mode: 0600
- name: Display resolv.conf contents
      command: cat resolv.conf chdir=/etc
      
- name: Print to console
      debug:
      msg: "{{command_output.stdout}}"      
